language: ruby
cache: bundler

before_install: gem install bundler -v '<2'

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.2.x
  - gemfiles/Gemfile.rails-5.2.x.sprockets-4.x
  - gemfiles/Gemfile.rails-6.0.x
  - gemfiles/Gemfile.rails-6.0.x.sprockets-4.x


notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "RkdRnCTQkmW7izb9+p9XB8pDrj7XiwHaOXQtEw29U7gXQDPqz77QzoL4cKlvMwalW77079Abp4gQpYeLFIZVm2VcVwFW3/6s0kgf3LGssbrF5fPSQnXk6GQGJBRGUyLt0TCi63Y/5DskREtEINbRfKLiDGm8ar/ExFoJzcZIsig="
